Update android.yml

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -19,6 +19,12 @@ jobs:
       env:
         DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
       run: echo $DATA > /home/runner/work/InfoPlay/InfoPlay/app/google-services.json
+    - name: Git pull
+      run: git push origin main
+    - name: Unignore Admob file
+      run: echo "git ls-files --error-unmatch app/src/main/res/values/admob_id.xml"
+    - name: Remover string/google_ad_mob_api_key do .gitignore
+      run: git rm --cached string/google_ad_mob_api_key && git commit -m "Remover string/google_ad_mob_api_key do .gitignore" || echo "Nenhum arquivo a ser removido"
     - name: Config github
       env:
         EMAIL: ${{ secrets.EMAIL }}
@@ -27,17 +33,10 @@ jobs:
         git config user.email $EMAIL
     - name: Git commit files
       run: git commit -m "key"
-    - name: Git pull
-      run: git push origin main
-    - name: Unignore Admob file
-      run: echo "git ls-files --error-unmatch app/src/main/res/values/admob_id.xml"
-    - name: Remover string/google_ad_mob_api_key do .gitignore
-      run: git rm --cached string/google_ad_mob_api_key && git commit -m "Remover string/google_ad_mob_api_key do .gitignore" || echo "Nenhum arquivo a ser removido"
     - name: Push das alterações para o repositório
       uses: ad-m/github-push-action@master
       with:
         github_token: ${{ secrets.TOKEN }}
-      
     - name: Grant execute permission for gradlew
       run: chmod +x gradlew
     - name: Build with gradle
